# Generated by Django 3.0.3 on 2023-02-05 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entry',
            name='blog',
        ),
        migrations.AlterField(
            model_name='entry',
            name='body_text',
            field=models.TextField(),
        ),
        migrations.DeleteModel(
            name='Blog',
        ),
    ]
