# Generated by Django 3.0.3 on 2021-10-17 18:13

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='body_text',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
    ]
